### ISSUE TITLE
"Doesnt work on all buttons"

### ISSUE THREAD

**Issue by zxxtlz** [vord1080/clipboard2file#10]
I like using roblox, and when i try to upload an image onto roblox, nothing pops up, the page looks like its trying to refresh
this is how the button looks ( if that helps in any way)
![firefox_Z5WXNr33DG](https://user-images.githubusercontent.com/75642081/193054191-9b1ecb2d-8be9-4c54-9d13-cc7530bc574e.png)

**Comment by vord1080** [comment]
This seems like a serious issue. Do you have a specific URL and steps to reproduce?

**Comment by zxxtlz** [comment]
Im pretty sure you need an account for the link to actually work,
but here you go
https://www.roblox.com/develop?View=2

**Comment by vord1080** [comment]
Alright, I know what the problem is. That file upload box exists inside an `iframe` which is too small for the popup. I have a development version of the extension that fixes this by always painting the popup in the parent frame instead. Hopefully I'll be able to get this new version out soon.

**Comment by zxxtlz** [comment]
Thank you for finding the issue!
Cant wait for the new update!

**Comment by vord1080** [comment]
The new version has been published. Please visit about:addons -> Extensions -> Gear Icon -> "Check for Updates" then verify that your installation of Clipboard2File is at version 3.2

Please confirm whether the issue is still present or not, thanks!

**Comment by zxxtlz** [comment]
It Works! thank you very much!

**Comment by vord1080** [comment]
epic
