### ISSUE TITLE
Doesn't work in AUTOMATIC111/stable-diffusion-webui

### ISSUE THREAD

**Issue by antage** [vord1080/clipboard2file#14]
[AUTOMATIC111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) is web UI for Stable Diffusion.

When I clicked "Upload" I get "file choose" system dialog.
I debug 'click' event propagation and `handleClick` has invoked and I see `event.target` doesn't contain `input[type=file]` but `event.originalTarget` does. It's because "AUTOMATIC111/stable-diffusion-webui" uses complex web framework (svelte.js).

I think `handleClick` may check both `event.target` and `event.originalTarget` to fix this issue.

**Comment by vord1080** [comment]
Is there a public version of this interface somewhere? I'd like to test this out

**Comment by antage** [comment]
https://huggingface.co/spaces/shideqin/stable-diffusion-webui

"img2img" or "PNG info" tabs have upload buttons.

**Comment by vord1080** [comment]
I don't see the problem. When I click "Drop Image Here/Click to Upload", the extension does work and I'm able to paste the image. Would you be able to create a screen recording of you getting the bug to happen?

**Comment by antage** [comment]
I confirm that capture2file works on public URL. But it doesn't work with locally running site.

https://www.youtube.com/watch?v=TrbCTItEGpY

**Comment by vord1080** [comment]
Yes, I do not understand why this happens. I can also see the same thing, when I open the iframe from huggingface.co in a new tab, the extension does not work. When the page is inside the frame, the extension does work. Conceptually, this makes no sense to me, in fact this could be a bug in Firefox.

**Comment by vord1080** [comment]
OK, i no longer think it is exactly a bug in Firefox. When the page is inside the iframe, there is no shadow root. When the page is opened directly, there is a shadow root, thats weird. So it looks like the issue is with shadow DOM event bubbling, very complicated and hard to fix.

**Comment by vord1080** [comment]
So the problem is that Shadow DOM events are bubbled up the shadow boundary, but not exactly. The reason the extension doesn't work is because our event listener is attached to `document.documentElement` root of the page. So when you click anything inside a shadow element, the page just sees the shadow element being clicked, not any children, so we cant detect the file input picker. Using originalTarget fixes this in some cases, but breaks others.....
