### ISSUE TITLE
Stopped working on Nightly

### ISSUE THREAD

**Issue by Caspy7** [vord1080/clipboard2file#17]
I run Nightly as my main driver. The other day I noticed that when I went to click on a link that would normally paste from the clipboard (a file browser link) that nothing happened.

I disabled the addon and reloaded the page and the file chooser window pops open as expected, but when enabled nothing happens. I tested on a release profile and it works as expected.

`dom.events.asyncClipboard.clipboardItem` is toggled to true.

I am on the most recent Nightly build.

**Comment by KK-Designs** [comment]
This is also happening to me, I am getting `Error: Could not establish connection. Receiving end does not exist.` in the console

**Comment by vord1080** [comment]
i think this is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1837370

please leave a comment on that bug to inform mozilla. I don't think there's anything can be done on our side to fix the problem.

**Comment by KK-Designs** [comment]
It works now!!
