### ISSUE TITLE
Didn't work in mozilla firefox

### ISSUE THREAD

**Issue by herconaryangga15** [vord1080/clipboard2file#2]
Excuse, the extension's not working for my Mozilla firefox I don't know why. I just installed but when uploading something in google images and imgur, it still asks me for choosing from my drive directory. Thanks

https://user-images.githubusercontent.com/92993341/145712807-0857fb6f-23d4-40cb-81fa-1a1cb058ba55.mp4

**Comment by vord1080** [comment]
The addon will not work until you set the pref dom.events.asyncClipboard.read to true in about:config
Does the extension work after doing this? 

Thanks

**Comment by herconaryangga15** [comment]
> The addon will not work until you set the pref dom.events.asyncClipboard.read to true in about:config Does the extension work after doing this?
> 
> Thanks

How do I find/do that?

**Comment by vord1080** [comment]
> > The addon will not work until you set the pref dom.events.asyncClipboard.read to true in about:config Does the extension work after doing this?
> > Thanks
> 
> How do I find/do that?

Navigate to about:config
Type dom.events.asyncClipboard.read in the searchbox
Double click "false" so it turns into "true", then exit about:config
https://support.mozilla.org/en-US/kb/about-config-editor-firefox

**Comment by herconaryangga15** [comment]
> > > The addon will not work until you set the pref dom.events.asyncClipboard.read to true in about:config Does the extension work after doing this?
> > > Thanks
> > 
> > 
> > How do I find/do that?
> 
> Navigate to about:config Type dom.events.asyncClipboard.read in the searchbox Double click "false" so it turns into "true", then exit about:config https://support.mozilla.org/en-US/kb/about-config-editor-firefox

Okay it works Thanks a lot!!
