### ISSUE TITLE
Doesn't work on all sites

### ISSUE THREAD

**Issue by msrn** [vord1080/clipboard2file#3]
Extension doesn't work on all sites.
The upload dialog doesn't work at all and the clipboard popup doesn't appear either.
Currently I have identified two sites in which this extension doesn't work. Moodle and finnish imageboard Ylilauta.org. You can test former here [here, by trying to create a new thread and picking an image](https://ylilauta.org/international/).

https://user-images.githubusercontent.com/14147811/151515838-e098c89f-c216-4793-a22b-ed42f4e31a21.mp4

**Comment by vord1080** [comment]
Yes, this is very bad. Thank you for discovery! I have feared this problem for a long time. The website is using very strict content security policy and this blocks the stylesheet from loading. We should both see this same error in console
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).

We need to find a workaround that will allow the popup to load without compromising the content security policy I think

**Comment by vord1080** [comment]
> Extension doesn't work on all sites. The upload dialog doesn't work at all and the clipboard popup doesn't appear either. Currently I have identified two sites in which this extension doesn't work. Moodle and finnish imageboard Ylilauta.org. You can test former here [here, by trying to create a new thread and picking an image](https://ylilauta.org/international/).
> moodle_clipboard2file.mp4

I pushed an update to the add-on that may have fixed your problem. Please upgrade the add-on and report back with your findings, thanks!

**Comment by msrn** [comment]
Thanks for the swift response! It now works correctly on ylilauta.org, but not on Moodle.
I can provide more debugging data for you if needed.

**Comment by vord1080** [comment]
> Thanks for the swift response! It now works correctly on ylilauta.org, but not on Moodle. I can provide more debugging data for you if needed.
> 
> Edit: Found a demo site for Moodle
> 
> https://sandbox.moodledemo.net/
> 
> You can test file uploading on the [private files page](https://sandbox.moodledemo.net/user/files.php) , just click the little document icon or drag-and-drop space

I have pushed an additional revision of the add-on. Please upgrade and report your findings again, thanks!

**Comment by msrn** [comment]
It works, just as excepted! Closing this, thank you :)

**Comment by vord1080** [comment]
> It works, just as excepted! Closing this, thank you :)
> 
> Edit: It seems you left some debugging comments in the code with commit [f638f2e](https://github.com/vord1080/clipboard2file/commit/f638f2ef735b9ab4919aae775f4b4cd3c6bef1a7) :P
> 
> https://github.com/vord1080/clipboard2file/blob/f638f2ef735b9ab4919aae775f4b4cd3c6bef1a7/content_script/content.js#L13
> 
> https://github.com/vord1080/clipboard2file/blob/f638f2ef735b9ab4919aae775f4b4cd3c6bef1a7/content_script/content.js#L99

Oops, I will fix these! Thank you for noticing :)
