### ISSUE TITLE
Extension doesn't seem to work on Firefox Developer Edition 102.0b6

### ISSUE THREAD

**Issue by Resident007** [vord1080/clipboard2file#7]
As title states, the extension doesn't seem to work anymore since some version 102. dom.events.asyncClipboard.read is set to **true** in about:config. I can help by providing any logs or other things you might need.

**Comment by vord1080** [comment]
Yeah, the preference changed in Firefox 102 ([bug 1766860](https://bugzilla.mozilla.org/show_bug.cgi?id=1766860)). Now you need to set **dom.events.asyncClipboard.clipboardItem** to **true** in about:config, please report back whether or not this works, thanks! :smile:

**Comment by Resident007** [comment]
Yep, works now, thanks a lot! I guess it needs to be mentioned in the description of the add-on.
