### ISSUE TITLE
Dosen't work altough preferences are set

### ISSUE THREAD

**Issue by loanto-ant** [vord1080/clipboard2file#9]
Hey, I just downloaded your extention and in about:config I have set _dom.events.asyncClipboard.clipboardItem_ to _true_ and also _dom.events.asyncClipboard.read_ to _true_. Unfortunately it still doesn't show the popup. Just the normal drive directory appears. Thanks.

**Comment by vord1080** [comment]
What is your Firefox version? and did you try restarting Firefox? And which sites did you try it on?

**Comment by loanto-ant** [comment]
I'm on firefox version 104.0.1. Yes I restarted firefox and I tried it on [imgur.com](https://imgur.com/upload) as well as [this site](https://www.filestack.com/fileschool/html/html-file-upload-tutorial-example/).
I just found my mistake and it works now. Sorry that I bothered you
